### ISSUE TITLE
Thank you for your video tutorial. I am a beginner and I have a question. I hope you can answer it.

### ISSUE THREAD

**Issue by 8-unlimit** [ytdeepia/Latent-Space-Visualisation-PCA-t-SNE-UMAP#1]
This function is in `part2/test.ipynb`，Does this function actually calculate the similarity between points?
I can't understand it very well, especially this  ` norm =  1/ (1 + np.linalg.norm(points[i] - points[j]) ** 2)` 
Why write a for loop if you don’t accumulate norm?
When I try to accumulate norm values, the shape of the final visualized graph does not change, only the value of the ordinate changes.
``` Compute the quantity q_ij for each point
def pij(points, x):
    norm = 0
    for i in range(len(points)):
        for j in range(len(points)):
            if i == j:
                continue
            norm =  1/ (1 + np.linalg.norm(points[i] - points[j]) ** 2)
    q = 0
    for j in range(len(points)):
        q += np.exp(-np.linalg.norm(x - points[j]) ** 2)
    
    q = q / norm
    
    return q

**Comment by ytdeepia** [comment]
Hi ! 

This function is not correct and does not compute the quantity it's supposed to compute. 
I did not correct this version as I did not include this visualisation in the final video. 
However, I think the correct version would be something like that:
```python
def pij(points, x):
    norm = 0
    for i in range(len(points)):
        for j in range(len(points)):
            if i == j:
                continue
            norm +=  (1 + np.linalg.norm(points[i] - points[j]) ** 2)
    q = 0
    for j in range(len(points)):
        q += np.exp(-np.linalg.norm(x - points[j]) ** 2)
    
    q = q / norm
    
    return q
```

Hope this helps !
